FROM amd64/python:3.7-slim-buster

RUN apt update && \
    apt install -y python3-opencv

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD [ "python3", "-u", "./main.py" ]